#!/bin/bash
mkdir -p Pictures
for file in PicSrc/*.pdf; do
    inkscape $file --export-type="svg" -o Pictures/`basename $file .pdf`.svg
    # iperender -svg $file Pictures/`basename $file .pdf`.svg  2>> errors.log || true;
done;
cp PicSrc/*.pdf Pictures/
