# Preface {.unnumbered}

These are notes used by the author on part of a course on *Advanced Number Theory*
taught at UB/UAB during Spring 2024. They evolved from a course on Modular Forms taught at the University of Warwick during autumn of 2015,
and are based on a variety of sources, mainly:

1. The books @diamond-shurman and @serre2012 listed in the bibliography.
2. Notes from a course taught by Peter Bruin in the spring term of 2014, which in turn are based on
3. Notes from a course taught by David Loeffler in the autumn term of 2011;
4. Notes from a course taught by Scott Ahlgren (UIUC) in 2006.


Typeset with Quarto. To learn more about it, see <https://quarto.org/docs/books>.

Licensed under the Creative Commons Attribution-NonCommercial 3.0 Unported License (the "License"). You may not use this file except in compliance with the License. You may obtain a copy of the License at \url{http://creativecommons.org/licenses/by-nc/3.0}. Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an \textsc{``as is'' basis, without warranties or conditions of any kind}, either express or implied. See the License for the specific language governing permissions and limitations under the License.
